all: chat-client.c
	cc $(CFLAGS) chat-client.c -o chat-client -lm

CFLAGS=-g

client: chat-client.c
	cc $(CFLAGS) chat-client.c -o chat-client -lm

clean:
	rm -f chat-clientall: chat-client.c
	cc $(CFLAGS) chat-client.c -o chat-client -lm

CFLAGS=-g

client: chat-client.c
	cc $(CFLAGS) chat-client.c -o chat-client -lm

clean:
	rm -f chat-client